### ISSUE TITLE
Also show OSM notes where a user only takes part in discussion ...

### ISSUE THREAD

**Issue by stephan75** [mapbox/osm-comments-frontend#51] opened 2016-01-27 17:11 UTC
... but another user created that note.

If I am not wrong, this service only displays OSM noted that a specific user has **created**.

So you can see your own OSM notes, and filtering about open or closed status.

Is it possible in general to display all OSM notes where  a specific user (the one you can query for) left a comment, but the OSM note was created by another user?

**Comment by batpad** [comment] 2016-01-27 17:18
Thanks for the issue, @stephan75 . This should be fixed by https://github.com/mapbox/osm-comments-api/issues/44 . Would be adding a parameter called `involves`, that one can use even on the front-end, to find all notes and changesets that a particular user is involved with (either as creator or as a participant).

Closing here since the issue is captured there. Thanks again.

**Closed as completed by batpad** 2016-01-27 17:18 UTC
