### ISSUE TITLE
osm-comments not updating?

### ISSUE THREAD

**Issue by mikelmaron** [mapbox/osm-comments-frontend#60] opened 2016-04-19 17:15 UTC
https://www.openstreetmap.org/user/malenki/diary/38480

**Comment by batpad** [comment] 2016-04-19 18:05
The issue is that the `from` filter in `osm-comments` checks for the date of the changeset, not the comments. Have filed here: https://github.com/mapbox/osm-comments-api/issues/45 .

**Comment by batpad** [comment] 2016-04-19 19:22
Tracking here: https://github.com/mapbox/osm-comments/issues/61

Closing.

**Closed as completed by batpad** 2016-04-19 19:22 UTC
